// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT1DZoUgLDHPr6v4Pzd2C5kybI5W07mgY',
    appId: '1:484601611168:web:745e29175ef223a2f05ac5',
    messagingSenderId: '484601611168',
    projectId: 'chat-app-f5741',
    authDomain: 'chat-app-f5741.firebaseapp.com',
    storageBucket: 'chat-app-f5741.appspot.com',
    measurementId: 'G-SFS9JC36NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-MIVaEOYjfAWKhF622JDwhvzSNpymVc',
    appId: '1:484601611168:android:9084a5c91e03c684f05ac5',
    messagingSenderId: '484601611168',
    projectId: 'chat-app-f5741',
    storageBucket: 'chat-app-f5741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsygkrg-2C6ooxecdWOMz6pjFtYlg1NRU',
    appId: '1:484601611168:ios:0fb90923f7f13449f05ac5',
    messagingSenderId: '484601611168',
    projectId: 'chat-app-f5741',
    storageBucket: 'chat-app-f5741.appspot.com',
    iosClientId: '484601611168-6s1p0tkrdvujafgo6nta7tvcbkrgr8g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsygkrg-2C6ooxecdWOMz6pjFtYlg1NRU',
    appId: '1:484601611168:ios:500ce6675633f6a1f05ac5',
    messagingSenderId: '484601611168',
    projectId: 'chat-app-f5741',
    storageBucket: 'chat-app-f5741.appspot.com',
    iosClientId: '484601611168-arh8bqlaim1jnotn5uqpnpfo01u4d1g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
